### ISSUE TITLE
This is the title of my issue 

### ISSUE THREAD

**Issue by chasenunez** [ekopter/git-Practice#1]
Here is the body of my issue. 
I take issue with this! 
real umbridge has been taken. 
that is all. 
also i have attached a file
![eas_cropped squarer](https://user-images.githubusercontent.com/14095519/108840331-7d442080-75d6-11eb-900e-cd31686190c6.png)

**Comment by ekopter** [comment]
is it birds or bats? is there any way of knowing?

i'm sorry for your issue, maybe you should see a professional about it.

alternatively, you could try using more informative priors.

**Comment by ekopter** [comment]
fixed the code
