### ISSUE TITLE
problem here

### ISSUE THREAD

**Issue by ekopter** [ekopter/git-Practice#3]
https://github.com/ekopter/git-Practice/blob/515baca3b14b164e40529ad680feb193caefeeed/CODE/preprocess_data.py#L6

**Comment by chasenunez** [comment]
hmm, maybe i'll delete it

**Comment by chasenunez** [comment]
I don't have the ability to resolve this one, you'll have to resolve the issue.

**Comment by ekopter** [comment]
boom goes the dynamite
